### PR TITLE
Ember upgrade v3.24 v3.28

### PR DESCRIPTION
**Pull request by benjay10**
Ember upgrade v3.24 to v3.28 and more package bumps.

This was the only plugin still on an older Ember version and had some dependencies that would cause inconsistencies in the frontend-gelinkt-notuleren app.

Also fixed the dummy app title, that still displayed the title for the roadsign regulation plugin.

This PR includes a package-lock.json that is compatible with npm v8. Nothing really special had to be done for that.

### CODE REVIEW

**Comment by nvdk** [comment]
I know I've been at fault here as well, but we should probably be consistent and either switch to a newer node and npm version with the whole team or stick with was currently agreed: node 12 and npm 6

**Comment by benjay10** [comment]
I'm not saying we have to move to npm 8 (although that would be nice). I wanted to update this plugin to the new Ember LTS version, as this is the last of the editor plugins (?) that wasn't updated yet. Meanwhile, I wanted to make sure things would work fine on npm 8 in the event we were to make the switch. Maybe leaving the package-lock.json for npm 8 in place was not the right decision.

**Comment by nvdk** [comment]
For now at least, it's easier to merge if you revert the package-lock.json file back to the stone ages :)

**Review by lagartoverde — APPROVED** [review]
Is the package-lock retrocompatible? if so I don't see why would we revert it, if not I agree is better to go back to the old one.
Otherwise works fine, good job 👍

**Pull request merged**
